# Generated by Django 5.2.1 on 2025-06-03 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FallAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected_by', models.CharField(default='webcam', help_text="Source of detection (e.g. 'live_camera', 'upload_test').", max_length=64)),
                ('image_snapshot', models.ImageField(blank=True, help_text='Optional snapshot of the frame where the fall was detected.', null=True, upload_to='snapshots/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Any additional notes about this detection.')),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether an employee has marked this as reviewed.')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
