# Generated by Django 5.2.1 on 2025-06-04 09:30

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallalert',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Raw JSON output from YOLO (boxes, scores, keypoints, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='video_clip',
            field=models.FileField(blank=True, help_text='Optional short video clip around the fall detection.', null=True, upload_to=detection.models.clip_upload_to),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='yolo_class',
            field=models.CharField(blank=True, help_text="Class name predicted by YOLO (e.g. 'fall', 'person').", max_length=64),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='yolo_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score from YOLO model at detection time.', null=True),
        ),
        migrations.AlterField(
            model_name='fallalert',
            name='image_snapshot',
            field=models.ImageField(blank=True, help_text='Optional snapshot of the frame where the fall was detected.', null=True, upload_to=detection.models.snapshot_upload_to),
        ),
    ]
