# Generated by Django 5.2.1 on 2025-06-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_fallalert_metadata_fallalert_video_clip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fallalert',
            name='accuracy_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='accuracy_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accuracy_marked_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='is_accurate',
            field=models.BooleanField(blank=True, help_text='Whether this detection was accurate (True=accurate, False=false positive, None=not marked)', null=True),
        ),
    ]
