# Generated by Django 5.2.1 on 2025-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_fallalert_accuracy_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallalert',
            name='fall_state',
            field=models.CharField(blank=True, choices=[('monitoring', 'Monitoring'), ('alert', 'Alert'), ('urgent', 'Urgent'), ('recovered', 'Recovered')], help_text='État de la chute (monitoring, alert, urgent, recovered)', max_length=20),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='time_on_ground',
            field=models.FloatField(blank=True, help_text='Temps passé au sol en secondes', null=True),
        ),
    ]